class Strings():
	START_MESSAGE = "START MESSAGE"
	HELP_MESSAGE = "HELP MESSAGE"
	INFO_MESSAGE = "INFO MESSAGE"
	LINKS_MESSAGE = "LINKS MESSAGE"
	NO_CONTENT_IMAGE = "NO CONTENT IMAGE"
	NO_STYLE_IMAGE = "NO STYLE IMAGE"